language: python
python:
  - "3.9"

env:
  - DJANGO=3.2.7 DB=postgresql
services:
  - postgresql
install:
  - pip install -r requirements.txt
# before_script: 
#   - psql -c 'create database travis_ci_test;' -U postgres
script: 
  - python manage.py test
