language: python
python:
  - "3.9"

services:
  - postgresql

env:
  -DJANGO=4.0 DB=postgresql

before_script: postgresql -e 'create database proshop;' -u root

script: 
  - python manage.py test && flake8