# Generated by Django 4.0.1 on 2022-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/ecommerce-default-product.png', null=True, upload_to=''),
        ),
    ]
